# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tech_share.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tech_share.proto',
  package='sdk',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10tech_share.proto\x12\x03sdk\"\x1b\n\rPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\rPeopleRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"-\n\x0ePeopleResponse\x12\x1b\n\x06people\x18\x01 \x03(\x0b\x32\x0b.sdk.Person\"A\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x0c.sdk.Address\"(\n\x07\x41\x64\x64ress\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t2v\n\tTechShare\x12.\n\tGetPerson\x12\x12.sdk.PeopleRequest\x1a\x0b.sdk.Person\"\x00\x12\x39\n\nListPeople\x12\x12.sdk.PeopleRequest\x1a\x13.sdk.PeopleResponse\"\x00\x30\x01\x62\x06proto3')
)




_PERSONREQUEST = _descriptor.Descriptor(
  name='PersonRequest',
  full_name='sdk.PersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sdk.PersonRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=52,
)


_PEOPLEREQUEST = _descriptor.Descriptor(
  name='PeopleRequest',
  full_name='sdk.PeopleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='sdk.PeopleRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=84,
)


_PEOPLERESPONSE = _descriptor.Descriptor(
  name='PeopleResponse',
  full_name='sdk.PeopleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='sdk.PeopleResponse.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=131,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='sdk.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sdk.Person.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='sdk.Person.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='sdk.Person.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=198,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='sdk.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='sdk.Address.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='sdk.Address.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=240,
)

_PEOPLERESPONSE.fields_by_name['people'].message_type = _PERSON
_PERSON.fields_by_name['address'].message_type = _ADDRESS
DESCRIPTOR.message_types_by_name['PersonRequest'] = _PERSONREQUEST
DESCRIPTOR.message_types_by_name['PeopleRequest'] = _PEOPLEREQUEST
DESCRIPTOR.message_types_by_name['PeopleResponse'] = _PEOPLERESPONSE
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonRequest = _reflection.GeneratedProtocolMessageType('PersonRequest', (_message.Message,), dict(
  DESCRIPTOR = _PERSONREQUEST,
  __module__ = 'tech_share_pb2'
  # @@protoc_insertion_point(class_scope:sdk.PersonRequest)
  ))
_sym_db.RegisterMessage(PersonRequest)

PeopleRequest = _reflection.GeneratedProtocolMessageType('PeopleRequest', (_message.Message,), dict(
  DESCRIPTOR = _PEOPLEREQUEST,
  __module__ = 'tech_share_pb2'
  # @@protoc_insertion_point(class_scope:sdk.PeopleRequest)
  ))
_sym_db.RegisterMessage(PeopleRequest)

PeopleResponse = _reflection.GeneratedProtocolMessageType('PeopleResponse', (_message.Message,), dict(
  DESCRIPTOR = _PEOPLERESPONSE,
  __module__ = 'tech_share_pb2'
  # @@protoc_insertion_point(class_scope:sdk.PeopleResponse)
  ))
_sym_db.RegisterMessage(PeopleResponse)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'tech_share_pb2'
  # @@protoc_insertion_point(class_scope:sdk.Person)
  ))
_sym_db.RegisterMessage(Person)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'tech_share_pb2'
  # @@protoc_insertion_point(class_scope:sdk.Address)
  ))
_sym_db.RegisterMessage(Address)



_TECHSHARE = _descriptor.ServiceDescriptor(
  name='TechShare',
  full_name='sdk.TechShare',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=242,
  serialized_end=360,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPerson',
    full_name='sdk.TechShare.GetPerson',
    index=0,
    containing_service=None,
    input_type=_PEOPLEREQUEST,
    output_type=_PERSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListPeople',
    full_name='sdk.TechShare.ListPeople',
    index=1,
    containing_service=None,
    input_type=_PEOPLEREQUEST,
    output_type=_PEOPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TECHSHARE)

DESCRIPTOR.services_by_name['TechShare'] = _TECHSHARE

# @@protoc_insertion_point(module_scope)
