# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import tech_share_pb2 as protos_dot_tech__share__pb2


class TechShareStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPeople = channel.unary_unary(
        '/orami.TechShare/GetPeople',
        request_serializer=protos_dot_tech__share__pb2.PeopleRequest.SerializeToString,
        response_deserializer=protos_dot_tech__share__pb2.PeopleResponse.FromString,
        )


class TechShareServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPeople(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TechShareServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPeople': grpc.unary_unary_rpc_method_handler(
          servicer.GetPeople,
          request_deserializer=protos_dot_tech__share__pb2.PeopleRequest.FromString,
          response_serializer=protos_dot_tech__share__pb2.PeopleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'orami.TechShare', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
