# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/tech_share.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/tech_share.proto',
  package='orami',
  syntax='proto3',
  serialized_options=_b('Z\tgo/protos'),
  serialized_pb=_b('\n\x17protos/tech_share.proto\x12\x05orami\"\x1e\n\rPeopleRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"/\n\x0ePeopleResponse\x12\x1d\n\x06people\x18\x01 \x03(\x0b\x32\r.orami.Person\"C\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1f\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x0e.orami.Address\"(\n\x07\x41\x64\x64ress\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t2G\n\tTechShare\x12:\n\tGetPeople\x12\x14.orami.PeopleRequest\x1a\x15.orami.PeopleResponse\"\x00\x42\x0bZ\tgo/protosb\x06proto3')
)




_PEOPLEREQUEST = _descriptor.Descriptor(
  name='PeopleRequest',
  full_name='orami.PeopleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='orami.PeopleRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=64,
)


_PEOPLERESPONSE = _descriptor.Descriptor(
  name='PeopleResponse',
  full_name='orami.PeopleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='orami.PeopleResponse.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=113,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='orami.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orami.Person.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='orami.Person.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='orami.Person.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=182,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='orami.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='orami.Address.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='orami.Address.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=224,
)

_PEOPLERESPONSE.fields_by_name['people'].message_type = _PERSON
_PERSON.fields_by_name['address'].message_type = _ADDRESS
DESCRIPTOR.message_types_by_name['PeopleRequest'] = _PEOPLEREQUEST
DESCRIPTOR.message_types_by_name['PeopleResponse'] = _PEOPLERESPONSE
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeopleRequest = _reflection.GeneratedProtocolMessageType('PeopleRequest', (_message.Message,), dict(
  DESCRIPTOR = _PEOPLEREQUEST,
  __module__ = 'protos.tech_share_pb2'
  # @@protoc_insertion_point(class_scope:orami.PeopleRequest)
  ))
_sym_db.RegisterMessage(PeopleRequest)

PeopleResponse = _reflection.GeneratedProtocolMessageType('PeopleResponse', (_message.Message,), dict(
  DESCRIPTOR = _PEOPLERESPONSE,
  __module__ = 'protos.tech_share_pb2'
  # @@protoc_insertion_point(class_scope:orami.PeopleResponse)
  ))
_sym_db.RegisterMessage(PeopleResponse)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'protos.tech_share_pb2'
  # @@protoc_insertion_point(class_scope:orami.Person)
  ))
_sym_db.RegisterMessage(Person)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'protos.tech_share_pb2'
  # @@protoc_insertion_point(class_scope:orami.Address)
  ))
_sym_db.RegisterMessage(Address)


DESCRIPTOR._options = None

_TECHSHARE = _descriptor.ServiceDescriptor(
  name='TechShare',
  full_name='orami.TechShare',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=226,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPeople',
    full_name='orami.TechShare.GetPeople',
    index=0,
    containing_service=None,
    input_type=_PEOPLEREQUEST,
    output_type=_PEOPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TECHSHARE)

DESCRIPTOR.services_by_name['TechShare'] = _TECHSHARE

# @@protoc_insertion_point(module_scope)
